# Generated by Django 4.2.1 on 2023-05-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_recruiter_id_alter_seeker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
